### PR TITLE
Restore original position in sentinel callback

### PR DESCRIPTION
**Pull request by syohex**
This is related to #241.
CC: @angrybacon

### CODE REVIEW

**Comment by angrybacon** [comment]
Thank you for being that responsive! :)

I've tried your patch but I am still experiencing the issue I described. Are you still working on it?

**Comment by syohex** [comment]
Hmm, I confirmed #241 issue is fixed. Did you reload helm-ag or re-evaluate its function ?

**Comment by angrybacon** [comment]
Yeah, tried to re-evaluate and also tried to restart Emacs. Made sure my changes were taken into account with `(message)`.

**Comment by syohex** [comment]
I have merged this PR because this fixes some issue which may be different from yours.

**Pull request merged**
