### PR TITLE
Set default-directory in editing buffer

### PR DESCRIPTION
**Pull request by syohex**
This is necessary for searching from not current directory.
This is related to #92.

### CODE REVIEW

**Comment by jonEbird** [comment]
I figured you might have a more appropriate fix, however after pulling the latest commit its not working for me. When I invoke `helm-do-ag` it does not seem to be ever calling `helm-ag--edit` which you just patched. I know this because I called `edebug-defun` on that function, in order to troubleshoot it, but it just never got called.

**Comment by syohex** [comment]
It looks working.

#### Debugger works well
helm-ag


#### Editing result works well
helm-ag

**Comment by jonEbird** [comment]
I must not be invoking it the "correct" way. I'm still able to trigger the original problem if I:
1. Open a file in a sub-directory of a project
2. Invoke `helm-do-ag` and pass project's base directory. (Done automatically via `projectile` via `C-s p s s`)
3. Type my search, .e.g. "pip", then immediately type `C-x C-s` to save the helm-ag results in a buffer.
4. Within the saved buffer, any `C-o` to go to another result errors. 

I still do not believe I have invoked `helm-ag--edit` at any point and therefore my `default-directory` for the saved buffer is still off. 

Here is an attempt to record what happens with a sample setuptools project code: http://jonebird.com/helm-ag_error.gif

**Comment by syohex** [comment]
Thanks for information, I'll fix later.

**Comment by syohex** [comment]
I have fixed at #94. Please check.

**Pull request merged**
